# Generated by Django 4.1 on 2023-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_users', '0003_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('D', 'Declined'), ('A', 'Accepted'), ('NA', 'No Answer')], default='NA', max_length=2),
        ),
    ]
