# Generated by Django 4.1 on 2023-01-12 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_users', '0005_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_sent_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
